from typing import Optional, Dict, Any

def generate_prompt(domain: str, sub_domain: str, options: Optional[Dict[str, Any]] = None) -> str:
    base_prompt = f"Act as a seasoned property lawyer in India specializing in real estate {domain}. Your task is to draft {sub_domain} document that adheres to Indian property laws and best legal practices.\n\n"
    prompt = f""

    # Define prompt components for different sub-domains
    prompt_components = {
        "sale deed": {
            "context_scene": "Context:\nAct as a seasoned property lawyer in Maharashtra, India, specializing in real estate Property Sale and Purchase legal documentation. Your task is to draft a sale deed that adheres to Indian property law and best legal practices. The document must be legally sound, structured, and formatted in a professional manner.\n\nThe document involves two parties:\n\nVendor (Seller): The individual/entity legally selling the property.\nVendee (Buyer): The individual/entity purchasing the property.\nThe jurisdiction of the transaction is Maharashtra, India, and the document must comply with applicable property laws, registration requirements, and taxation provisions.\n\nThe property details should include location, ownership history, sale consideration, and legal encumbrances. The document should also ensure that title transfer, possession, and indemnification clauses are clearly established.\n\n",
            "objective": "Objective:\nDraft a Sale Deed that:\n\nFacilitates the legal transfer of ownership of a specified property from the Vendor to the Vendee.\nEnsures legal compliance with property transfer regulations under Indian law.\nProvides clarity on rights, obligations, warranties, indemnifications, and liabilities of both parties.\nIncludes a schedule of the property, detailing boundaries, measurements, and survey information.\n\n",
            "format": "Format:\nThe document should be structured in formal legal language, incorporating clear headings and numbered clauses. It should include:\n\nIntroduction:\n\nDate and place of execution\nVendor and Vendee details\nMention of General or Special Power of Attorney (if applicable)\nRecitals:\n\nVendor’s ownership details (how the property was acquired)\nConfirmation of Vendor’s right to sell\nAgreement on sale consideration\nMain Clauses:\n\nConveyance Clause: Legal transfer of ownership and possession\nEncumbrance Clause: Assurance of no existing liabilities on the property\nIndemnity Clause: Vendor’s liability for any undisclosed claims\nPossession Clause: Physical handover of property and related documents\nMutation and Registration Clause: Buyer’s right to update official records\nTax and Dues Clause: Vendor’s responsibility for past liabilities\nDispute Resolution Clause: Governing jurisdiction and legal recourse\nSchedule of the Property:\n\nPlot details, survey number, measurements\nBoundaries (East, West, North, South)\nMarket value\nExecution & Witness Section:\n\nSignatures of Vendor, Vendee, and Witnesses\nEnsure formal structure, precise legal terminology, and compliance with best practices in property documentation under Indian law."
        },
        "gift deed": {
            "context_scene": "Context:\nLegal Domain: Property Law (Gift Deed for Immovable Property).\nJurisdiction: India (adaptable to state-specific regulations, e.g., Karnataka, Maharashtra).\nParties Involved:\nDonor: The absolute owner who is gifting the property out of natural love and affection.\nDonee: The recipient who accepts the property as a gift without any monetary consideration.\nNature of Transaction:\nThe property (land, building, or both) is transferred irrevocably and includes all associated rights and liabilities.\nThe transfer must be executed voluntarily, without coercion, fraud, or undue influence.\nThe Donee will assume responsibilities, including property taxes and maintenance after acceptance.\n",
            "objective": "Objective:\nDraft a legally enforceable Gift Deed with the following provisions:\nOwnership Declaration: The Donor confirms absolute ownership and legal capacity to transfer.\nIrrevocable Transfer Clause: The gift is permanent and unconditional.\nRights & Liabilities: Donee has full rights to use, transfer, or modify the property.\nAssurances by Donor: The property is free from encumbrances, claims, or disputes.\nTax & Registration Responsibilities: Specifies who bears stamp duty and registration charges.\nLegal Acceptance by Donee: The Donee formally accepts the gift, making the transfer legally binding.\n",
            "format": "Format:\nUse formal legal language and a structured clause-based format with the following sections:\n\nTitle: \"Gift Deed\"\nPreamble/Recitals:\nDetails of Donor and Donee (Name, Age, Address, Occupation).\nBackground of the property and Donor’s ownership history.\nStatement of relationship between Donor and Donee.\nMain Clauses:\nDeclaration of Gift: Voluntary transfer by Donor without consideration.\nRight to Possession & Enjoyment: Donee’s legal right to use the property.\nLegal Warranties by Donor: Assurance of no pending litigation, claims, or liabilities.\nAcceptance Clause: The Donee formally accepts the gift.\nTaxation & Charges: Who bears stamp duty, registration fees, and government levies.\nSchedule of Property:\nDetailed description of property:\nProperty Number, Area, Dimensions.\nBoundaries (East, West, North, South).\nMarket Value of the Property.\nExecution Section:\nSignatures of Donor and Donee.\nAttestation by two witnesses.\nDeliver a legally binding Gift Deed draft that aligns with these specifications."
        },
        "agreement for sale": {
            "context_scene": "Context:\nAct as a seasoned property lawyer in India specializing in real estate Property Sale and Purchase legal documentation.Legal Domain: Property Law (Real Estate Transactions)\nJurisdiction: India (Adaptable to specific state laws like Karnataka, Maharashtra, etc.)\nParties Involved:\nSELLER: The absolute owner of the property\nPURCHASER: The buyer acquiring the property under specified terms\nBackground Information:\nThe SELLER is in possession of a residential/commercial property with clear and marketable title.\nThe PURCHASER has agreed to buy the property at a mutually agreed sale consideration.\nThe agreement will establish the terms of sale, payment structure, possession transfer, and legal obligations of both parties.",
            "objective": "Objective:\nDraft a legally sound and comprehensive Agreement for Sale between a seller and a purchaser.\nEnsure that the document:\nClearly defines the sale consideration, advance payment, and balance payment terms.\nOutlines the obligations of the seller, including delivering a clear title, obtaining necessary permissions, and ensuring no encumbrances.\nSpecifies the rights of the purchaser, including the ability to assign or nominate another party.\nIncludes indemnity clauses, dispute resolution terms, and provisions for specific performance in case of breach.",
            "format": "Format:\nUse formal legal language with precise legal terminology.\nThe document should include:\nTitle: \"Agreement for Sale\"\nIntroductory Clauses: Identifying the seller, purchaser, and property details.\nRecitals: Providing background on ownership, encumbrances, and agreement to sell.\nMain Clauses:\nSale consideration and payment structure\nPossession and execution of the Sale Deed\nSeller’s warranties and title assurance\nBuyer’s rights and obligations\nDispute resolution mechanism\nIndemnity and liabilities\nStamp duty and registration charges\nSchedule of Property: Describing property dimensions, boundaries, and building details.\nSignatures & Witnesses Section: Ensuring legal enforceability.\n\nAdditional Considerations:\nEnsure that possession transfer conditions comply with The Transfer of Property Act, 1882.\nInclude necessary state-specific stamp duty and registration requirements (e.g., Karnataka Stamp Act, 1957).\nThe agreement must be structured in a clear, clause-based format to avoid ambiguity and legal disputes.\nDeliver a legally binding draft that meets these specifications."
        },
        "commercial lease agreement": {
            "context_scene": "Context:\nLegal Domain: Commercial Lease Law\nJurisdiction: [Specify the governing jurisdiction, e.g., Maharashtra, India]\nParties Involved:\nLessor (Landlord): The owner of the property, granting the lease.\nLessee (Tenant): The business entity or individual leasing the commercial space.\nProperty Details: [Include details such as address, type of commercial property (e.g., office space, retail store, warehouse), square footage, and permitted use.]\nLease Term: [Specify duration, e.g., 5 years with renewal options.]\nPayment Terms: [Specify rent amount, payment frequency, security deposit, escalation clause.]\nPurpose of Agreement: To define the terms and conditions under which the Lessee can occupy and use the commercial premises while ensuring the Lessor’s interests are protected.\n",
            "objective": "Objective:\nDraft a detailed Commercial Lease Agreement that outlines the rights, obligations, and liabilities of both parties.\nEnsure compliance with local real estate and commercial lease laws.\nInclude standard clauses along with any customized provisions based on the jurisdiction and business requirements.\n",
            "format": "Format:\nUse clear, structured, and legally precise language.\nInclude the following key clauses:\nPremises Description – Detailed description of the leased property.\nLease Term & Renewal – Duration, renewal options, and conditions.\nRent & Payment Terms – Monthly rent, due dates, late fees, escalation.\nSecurity Deposit – Amount, refund conditions, and deductions.\nPermitted Use – Business activities allowed on the premises.\nMaintenance & Repairs – Responsibilities of the Lessor and Lessee.\nAlterations & Improvements – Conditions for modifications to the property.\nInsurance & Liability – Who bears responsibility for property damage or personal injury.\nSubleasing & Assignment – Conditions for subletting or transferring lease rights.\nTermination & Eviction – Grounds for termination, notice period, penalties.\nDispute Resolution – Arbitration, mediation, or litigation provisions.\nForce Majeure – Handling unforeseen circumstances affecting the lease.\nGoverning Law – Applicable legal framework.\nEnsure all sections are clearly labeled and numbered for easy reference.\nAdditional Considerations:\nIf required, include industry-specific clauses (e.g., signage rights for retail leases, parking allocations).\nThe agreement should be binding and legally enforceable.\nAvoid ambiguous language and ensure all obligations are clearly defined.\nGenerate the Commercial Lease Agreement based on this structured framework, ensuring compliance with [Jurisdiction] laws and best legal practices."
        },
        "partition deed": {
        "context_scene": "Context (Setting the Scene):\nAct as a seasoned property lawyer specializing in Hindu property law in Maharashtra, India. You are drafting a Partition Deed for a Hindu Undivided Family (HUF) undergoing partition of its joint family property. The parties involved are co-parceners of the joint family, and the properties to be partitioned include land and buildings described in the schedules attached to the deed. The purpose of this document is to legally divide and transfer ownership of these properties among the family members, ensuring that each party receives a specific portion of the property, thereby severing their joint ownership.\n\n",
        "objective": "Objective (Defining the Task):\nDraft a legally sound Partition Deed that:\n\nClearly identifies the parties involved (co-parceners of the HUF).\nEstablishes the background and intent for partitioning the joint family property.\nOutlines the division of property among the parties, specifying allocations based on mutually agreed terms.\nEnsures the deed includes grant, release, and discharge clauses that transfer full ownership rights to the respective parties.\nIncorporates covenants ensuring the legitimacy of the transfer and freedom from future claims.\nDetails title deed custody arrangements and clarifies obligations regarding tax payments, assessments, and municipal dues.\nFollows legal best practices in Maharashtra, adhering to Hindu property laws and ensuring enforceability.\n\n",
        "format": "Format (Specifying the Output Structure):\n\nThe document should be in a formal legal format, following a clause-by-clause structure with clear headings and subheadings.\nBegin with a title, date, and place of execution.\nList all parties involved with full details.\nInclude “Whereas” clauses to establish the background.\nDraft numbered clauses detailing:\nThe partition agreement and property allocation.\nGrant and release of ownership rights.\nCovenants ensuring clear transfer of property.\nProvisions for execution, registration, and possession of title deeds.\nWitness section with signature blocks.\nProvide attached schedules listing the properties and their allocations.\nMaintain precise legal terminology while ensuring clarity and enforceability.\nFew-Shot Example (Reference Style & Key Clauses):\nThe format should resemble standard partition deeds used in India, such as:\n\n\"NOW THIS DEED WITNESSETH AS FOLLOWS:\" followed by structured legal clauses.\nCovenants ensuring no future claims arise.\nGrant and release clauses ensuring full ownership transition.\nTitle deed custody agreements to establish future document handling.\nRole Assignment (Adding Expertise):\nAct as a highly experienced legal professional specializing in Hindu family property law in Maharashtra. Ensure that the Partition Deed adheres to the Hindu Succession Act, Registration Act, and Transfer of Property Act, while maintaining clarity, enforceability, and compliance with local regulations. The document must be legally valid, clearly structured, and suitable for registration with the relevant authorities.\n\nExpected Output:\nA legally sound Partition Deed ready for execution and registration. Ensure all clauses, formatting, and terminology are suitable for practical legal use."
        },
        "residential rental agreement": {
        "context_scene": "Context:\nThe Lessor (Landlord) is the lawful owner of the property, and the Lessee (Tenant) wishes to lease the premises for residential purposes.\nThe lease will commence on [Lease Start Date] for a term of [Lease Term] with an agreed monthly rent of [Monthly Rental in Number & Words].\nThe agreement must include provisions on security deposit, maintenance responsibilities, termination rights, and rent payment terms.\nThe lease should also cover utilities, repairs, alterations, entry rights, and legal compliance obligations of both parties.\n",
        "objective": "Objective:\nDraft a formal Residential Rental Agreement that ensures clarity, legal compliance, and fairness for both parties.\nThe document must outline key rights and obligations, including payment structure, termination conditions, permitted use, maintenance duties, default consequences, and security deposit terms.\nThe agreement should incorporate necessary indemnity clauses, dispute resolution mechanisms, and compliance with relevant housing regulations.\n",
        "format": "Format:\nThe agreement should follow a structured, clause-by-clause format with:\nClear headings and subheadings for each section.\nA signature block for the Lessor, Lessee, and two witnesses.\nAn annexure listing fixtures and fittings provided with the property.\nEnsure the language is precise, legally enforceable, and easy to understand while adhering to standard lease agreement conventions.\nGenerate the agreement in a formal legal tone, ensuring thoroughness and adherence to best legal practices."
        },
        "test":{
            "context_scene":"write in one line the intent of legal documents",
            "objective":"",
            "format":""
        }
    }

    sub_domain_lower = sub_domain.lower()
    if sub_domain_lower in prompt_components:
        prompt += prompt_components[sub_domain_lower]["context_scene"]
        prompt += prompt_components[sub_domain_lower]["objective"]
        prompt += prompt_components[sub_domain_lower]["format"]
    else:
        base_prompt

    if options:
        prompt += f"Options: {options}. "

    return prompt