"""deleting profile

Revision ID: 58e2a1d2db11
Revises: b3035d127c59
Create Date: 2025-05-26 17:25:08.858724

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '58e2a1d2db11'
down_revision: Union[str, None] = 'b3035d127c59'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'profile')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('profile', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
